spring:
  application:
    name: week6

  profiles:
    default: development

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:week6}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME:week6}
    password: ${DB_PASSWORD:week6}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB

file:
  upload-dir: ${FILE_UPLOAD_DIR:uploads/images}

jwt:
  secret: ${JWT_SECRET}
  access-token-exp-seconds: 300
  refresh-token-exp-seconds: 1209600