spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:week6}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            StatementCreatorUtils: info
            JdbcTemplate: info
      hibernate:
        SQL: info
    p6spy: debug

mock-data:
  enabled: ${MOCK_DATA_ENABLED:false}
