package org.ktb.week6.enums;

public enum ReportReason {
    SPAM, DUPLICATE_CONTENT, ABUSE, SEXUAL_CONTENT, VIOLENT_CONTENT, ILLEGAL_CONTENT, PERSONAL_INFO_EXPOSURE, COPYRIGHT_INFRINGEMENT, OFF_TOPIC, OTHER
}
